const ROLES = {
  STUDENT: 'student',
  STAFF: 'staff',
  OFFICER: 'officer',
  ADMIN: 'admin',
};

const COMPLAINANT_ROLES = [ROLES.STUDENT, ROLES.STAFF];

const STATUSES = {
  SUBMITTED: 'Submitted',
  ACKNOWLEDGED: 'Acknowledged',
  IN_PROGRESS: 'In Progress',
  RESOLVED: 'Resolved',
  CLOSED: 'Closed',
};

const PRIORITIES = {
  LOW: 'Low',
  MEDIUM: 'Medium',
  HIGH: 'High',
};

const SLA_DAYS = {
  [PRIORITIES.HIGH]: 2,
  [PRIORITIES.MEDIUM]: 5,
  [PRIORITIES.LOW]: 7,
};

const STATUS_TRANSITIONS = {
  [STATUSES.SUBMITTED]: [STATUSES.ACKNOWLEDGED],
  [STATUSES.ACKNOWLEDGED]: [STATUSES.IN_PROGRESS],
  [STATUSES.IN_PROGRESS]: [STATUSES.RESOLVED],
  [STATUSES.RESOLVED]: [STATUSES.CLOSED, STATUSES.IN_PROGRESS],
  [STATUSES.CLOSED]: [],
};

const COMMENT_MAX_LENGTH = 1000;
const COMMENT_MIN_LENGTH = 1;

const FEEDBACK_COMMENT_MAX_LENGTH = 500;
const FEEDBACK_RATING_MIN = 1;
const FEEDBACK_RATING_MAX = 5;

const ATTACHMENT_MAX_COUNT = 3;
const ATTACHMENT_MAX_SIZE_BYTES = 5 * 1024 * 1024;
const ATTACHMENT_ALLOWED_TYPES = ['image/jpeg', 'image/png', 'application/pdf'];
const ATTACHMENT_ALLOWED_EXTENSIONS = ['.jpg', '.jpeg', '.png', '.pdf'];

module.exports = {
  ROLES,
  COMPLAINANT_ROLES,
  STATUSES,
  PRIORITIES,
  SLA_DAYS,
  STATUS_TRANSITIONS,
  COMMENT_MAX_LENGTH,
  COMMENT_MIN_LENGTH,
  FEEDBACK_COMMENT_MAX_LENGTH,
  FEEDBACK_RATING_MIN,
  FEEDBACK_RATING_MAX,
  ATTACHMENT_MAX_COUNT,
  ATTACHMENT_MAX_SIZE_BYTES,
  ATTACHMENT_ALLOWED_TYPES,
  ATTACHMENT_ALLOWED_EXTENSIONS,
};
